name: CI rome
on: [push]
jobs:
  lint:
    name: Lint using rome
    runs-on: ubuntu-latest
    steps:
      - uses: rome/setup-rome@v0.4
        with:
          version: 12.0.0
      - uses: actions/checkout@v2
      - run: rome ci .
