name: CI rome
on: [push]
jobs:
  lint:
    name: Lint using rome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn rome ci .
      - name: Tests
        run: yarn test
