name: CI (lint + tests)
on: [push]
jobs:
  ci:
    name: Lint using rome & Tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Lint rome
        run: yarn rome ci .
      - name: Tests jest
        run: yarn test
